# Generated by Django 5.1.6 on 2025-02-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_credits',
            field=models.DecimalField(decimal_places=2, default=0.0,
                                      help_text='Available credits on the user dashboard.', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, help_text='Company name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the user.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, help_text="User's timezone.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_intent',
            field=models.CharField(blank=True,
                                   choices=[('early', 'Early Career Professional'), ('mid', 'Mid Level Professional'),
                                            ('executive', 'Executive'), ('c_suite', 'C-Suite'), ('athlete', 'Athlete'),
                                            ('entrepreneur', 'Entrepreneur')],
                                   help_text='Select your career/intention level at sign up.', max_length=50,
                                   null=True),
        ),
    ]
