# Generated by Django 5.1.6 on 2025-03-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_userprofile_available_credits_userprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('coach', 'Coach')], default='user',
                                   max_length=20),
        ),
    ]
