# Generated by Django 5.1.6 on 2025-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_userprofile_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purpose',
            field=models.CharField(
                choices=[('public_speaking', 'Public_speaking'), ('pitch', 'Pitch'), ('presenting', 'Presenting')],
                default='public_speaking', max_length=20),
        ),
    ]
