# Generated by Django 5.1.7 on 2025-04-01 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_userprofile_profile_picture'),
        ('users', '0005_alter_userprofile_purpose'),
    ]

    operations = [
    ]
