# Generated by Django 5.1.7 on 2025-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practice_reminder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_analysis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
