# Generated by Django 5.1.7 on 2025-04-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_userprofile_email_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Media & Presentation', 'Media & Presentation'),
                                                        ('Technology', 'Technology'), ('Healthcare', 'Healthcare'),
                                                        ('Finance', 'Finance'), ('Education', 'Education'),
                                                        ('entrepreneur', 'Entrepreneur')], max_length=50, null=True),
        ),
    ]
