# Generated by Django 5.1.7 on 2025-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_userprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Media & Presentation', 'Media & Presentation'),
                                                        ('Technology', 'Technology'), ('Healthcare', 'Healthcare'),
                                                        ('Finance', 'Finance'), ('Education', 'Education')],
                                   max_length=50, null=True),
        ),
    ]
