# Generated by Django 5.1.7 on 2025-04-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_userprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='available_credits',
            field=models.DecimalField(decimal_places=2, default=4.0,
                                      help_text='Available credits on the user dashboard.', max_digits=10),
        ),
    ]
