# Generated by Django 5.2 on 2025-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_alter_userprofile_available_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quickbooks_customer_id',
            field=models.CharField(blank=True, help_text='QuickBooks Customer ID linked to this user.', max_length=100,
                                   null=True, unique=True),
        ),
    ]
