# Generated by Django 5.2 on 2025-04-28 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_customuser_has_logged_in_alter_userprofile_purpose_and_more'),
        ('users', '0012_userprofile_quickbooks_customer_id'),
    ]

    operations = [
    ]
