# Generated by Django 5.1.7 on 2025-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20250428_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Media & Presentation', 'Media & Presentation'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
